### ISSUE TITLE
cgcloud -IT fails with missing lib source distribution

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#132]
This is cgcloud 1.3.7, installed like so

```
virtualenv venv
source venv/bin/activate
pip install cgcloud-toil
pip install cgcloud-core
pip install cgcloud-jenkins
```

`cgcloud create -IT toil-box > log 2>err`

last lines of [log file](http://hgwdev.cse.ucsc.edu/~jeltje/toil/libError.err):

```
[52.37.36.100] out: Installed /opt/cgcloudagent/lib/python2.7/site-packages/pip-1.5.2-py2.7.egg
[52.37.36.100] out: Processing dependencies for pip==1.5.2
[52.37.36.100] out: Finished processing dependencies for pip==1.5.2
[52.37.36.100] out:
```

last lines of [error file](http://hgwdev.cse.ucsc.edu/~jeltje/toil/libError.err):

```
    return [ project_artifact( 'lib' ), project_artifact( project_name ) ]
  File "/data/git/toil-scripts/src/toil_scripts/rnaseq_cgl/venv/local/lib/python2.7/site-packages/cgcloud/core/project.py", line 56, in project_artifact
    project_name, sdist_glob) )
RuntimeError: Can't find 'lib' source distribution. Looking for '/data/git/lib/dist/cgcloud-lib*.tar.gz'. You may just need to run 'make sdist' to fix this
```

Note that it is looking in a directory that is more or less logical on my system: `/data/git` but I have no clue why it's looking for a `lib` there.

**Comment by hannes-ucsc** [comment]
Can you activate that venv and then run 

```
pip list
env | grep PYTHON
env | grep /data/git
```

**Comment by Jeltje** [comment]
`pip list`

```
argparse (1.2.1)
bd2k-python-lib (1.11.dev6)
boto (2.38.0)
cgcloud-core (1.3.7)
cgcloud-jenkins (1.3.7)
cgcloud-lib (1.3.7)
cgcloud-mesos (1.3.7)
cgcloud-toil (1.3.7)
ecdsa (0.13)
Fabric (1.10.2)
paramiko (1.16.0)
pip (1.5.4)
pycrypto (2.6.1)
PyYAML (3.11)
setuptools (2.2)
wsgiref (0.1.2)
```

No results for `env | grep PYTHON`
`env | grep /data/git`

```
OLDPWD=/data/git/cgcloud
VIRTUAL_ENV=/data/git/toil-scripts/src/toil_scripts/rnaseq_cgl/venv
PATH=/data/git/toil-scripts/src/toil_scripts/rnaseq_cgl/venv/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/data/git/toil-scripts/src/toil_scripts/rnaseq_cgl
```

**Comment by hannes-ucsc** [comment]
The cgcloud venv is inside the toil_scripts source tree. That's highly unorthodox and might be the cause but I can't be sure. I recommend sticking with the installation procedure for cgcloud as described in the READMEs. They suggest putting the virtualenv in ~/cgcloud. Can you remove /data/git/toil-scripts/src/toil_scripts/rnaseq_cgl/venv and then follow:

https://github.com/BD2KGenomics/cgcloud/blob/master/core/README.rst#installation 

?

**Comment by Jeltje** [comment]
There is some method to my madness - I've been having so much trouble with the different versions that I now keep my venvs in my working directories. That way I can at least check what the last working version was. 

Anyway, doing it as suggested completely fixed the issue. I will better my ways!
