### ISSUE TITLE
"--zone" on every command line is annoying

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/cgcloud#153]
There should be a way to set the default zone so it isn't required for every command.  If there already is one, it should be documented.

**Comment by hannes-ucsc** [comment]
That's what the CGCLOUD_ZONE environment variable is for. Run `cgcloud create --help` for details (look for --zone). Feel free to reopen if you feel that this is not sufficient.

**Comment by tetron** [comment]
Sorry about that, I must have overlooked that section.
