### ISSUE TITLE
cgcloud creation fails for lack of VPC resource 

### ISSUE THREAD

**Issue by deanasnyder** [BD2KGenomics/cgcloud#163]
I went through the steps outlined here
     https://github.com/BD2KGenomics/cgcloud/blob/master/core/README.rst 
but noted the following problems:
- I tried following the advice there - “Instead of us-west-2a you could use us-east-1a or any other zone in any other EC2 region.” - and set the zone to us-east-1a, but got an error message that said I needed to be in the us-west-2a zone. (Sorry I didn't keep it and I can't reproduce it now.)
- So I set it back to the zone back us-west-2a, but am now getting this error : 

```
<Code>VPCResourceNotSpecified
<Message>The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
```

Upon advice from cgcloud developers I added -t t1.micro to the commands "cgcloud create generic-ubuntu-trusty-box" and  "cgcloud create -IT spark-box" and they worked.

Here’s the complete terminal output from the failed run:

```
(cgcloud) deansmacbook*dean 13:49:31 ~ : cgcloud create generic-ubuntu-trusty-box
INFO: Using zone 'us-west-2a' and namespace '/dean/'
INFO: Looking up default image for role generic-ubuntu-trusty-box and virtualization type hvm, ...
INFO: ... found ami-adcb36cd.
INFO: Creating t2.micro instance(s) ...
Traceback (most recent call last):
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/bin/cgcloud", line 11, in <module>
    sys.exit(main())
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/lib/util.py", line 300, in run
    command.run( options )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 81, in run
    return self.run_in_ctx( options, ctx )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 105, in run_in_ctx
    return self.run_on_role( options, ctx, role )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 124, in run_on_role
    return self.run_on_box( options, box )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 471, in run_on_box
    box.terminate( wait=False )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 466, in run_on_box
    box.create( spec, wait_ready=True )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 563, in create
    reservation = self._create_ondemand_instances( spec )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 630, in _create_ondemand_instances
    return self.ctx.ec2.run_instances( self.image_id, **spec )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VPCResourceNotSpecified</Code><Message>The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.</Message></Error></Errors><RequestID>026230b1-263b-4a1c-aa74-03af1aa5dd9e</RequestID></Response>
```

What should I do to get  >t1.micro creation?

**Comment by hannes-ucsc** [comment]
Hi @deanasnyder,

Can you follow the steps outlined in the `Detecting Platform Support Using the Console` section of the document below for the us-east-1 and us-west-2 regions and post here what the console shows for `Supported platforms` and `Default VPC`?

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/default-vpc.html#detecting-platform-console

**Comment by deanasnyder** [comment]
Yeah, my EC2 Dashboard says:

```
Supported Platforms
EC2
VPC
```

which indicates that we fall in the category of pre-2013 AWS accounts (which is true), and therefore do not have a default VPC. See the following from the VPC FAQs http://aws.amazon.com/vpc/faqs/#Default_VPCs:

> Q. I really want a default VPC for my existing EC2 account. Is that possible?
> 
> Yes, however, we can only enable an existing account for a default VPC if you have no EC2-Classic resources for that account in that region. Additionally, you must terminate all non-VPC provisioned Elastic Load Balancers, Amazon RDS, Amazon ElastiCache, and Amazon Redshift resources in that region. After your account has been configured for a default VPC, all future resource launches, including instances launched via Auto Scaling, will be placed in your default VPC. To request your existing account be setup with a default VPC, contact AWS Support. We will review your request and your existing AWS services and EC2-Classic presence to determine if you are eligible for a default VPC.

So I am in the process of doing just this.

But shouldn't your scripts allow for this account state in its decision tree? - especially for those users in AWS zones where no default VPC is even possible?

**Comment by hannes-ucsc** [comment]
> But shouldn't your scripts allow for this account state in its decision tree? - especially for those users in AWS zones where no default VPC is even possible?

Absolutely. We just never ran into this until now. I wanted to make sure that lack of default VPC is indeed the culprit here. I am assuming that adding a `--vpc` switch and corresponding CGCLOUD_VPC environment variable would cover this use case.

**Comment by deanasnyder** [comment]
Beautiful! When can we expect a fix? ;-)

> We just never ran into this until now.

So all your users are AWS newbies, born since 2013? ;-)  (I'm feeling old school about now.)

Thanks for your quick and knowledgable responses.

**Comment by hannes-ucsc** [comment]
A fix should go in today. Would you be available to test it for us?

**Comment by deanasnyder** [comment]
Yes.

**Comment by hannes-ucsc** [comment]
The fix has been merged. CI is building an unstable release containing the fix right now. I'll update this issue when that is done.

**Comment by hannes-ucsc** [comment]
https://pypi.python.org/pypi?:action=display&name=cgcloud-core&version=1.4a1.dev286

includes the fix and can be installed with `pip install --pre --upgrade …` but check pip's output to verify that it indeed installs 1.4a1.dev286. Older pip's behave weirdly in this respect. 

Please reopen if fix does not work. Thank you for contributing.

**Comment by deanasnyder** [comment]
I did:

```
$ source /Users/dean/Documents/CIDR/ADAM/cgcloud/bin/activate
(cgcloud) $ pip install --pre --upgrade cgcloud-core
(cgcloud) $ cgcloud create -IT toil-box
```

and got the same error:
   `... VPCResourceNotSpecified ...`

Here's the output from the pip install:

```
(cgcloud) $ pip install --pre --upgrade cgcloud-core
Collecting cgcloud-core
  Using cached cgcloud-core-1.4a1.dev286.tar.gz
Collecting bd2k-python-lib>=1.11.dev6 (from cgcloud-core)
  Using cached bd2k-python-lib-1.13.dev16.tar.gz
Collecting cgcloud-lib==1.4a1.dev286 (from cgcloud-core)
  Using cached cgcloud-lib-1.4a1.dev286.tar.gz
Collecting futures==3.0.4 (from cgcloud-core)
  Using cached futures-3.0.4-py2-none-any.whl
Requirement already up-to-date: boto==2.38.0 in ./Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages (from cgcloud-core)
Collecting Fabric==1.10.3 (from cgcloud-core)
  Using cached Fabric-1.10.3-py2-none-any.whl
Collecting paramiko==1.16.0 (from cgcloud-core)
  Using cached paramiko-1.16.0-py2.py3-none-any.whl
Requirement already up-to-date: PyYAML==3.11 in ./Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages (from cgcloud-core)
Collecting subprocess32==3.2.7 (from cgcloud-core)
  Using cached subprocess32-3.2.7.tar.gz
Requirement already up-to-date: pycrypto!=2.4,>=2.1 in ./Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/pycrypto-2.6.1-py2.7-macosx-10.11-intel.egg (from paramiko==1.16.0->cgcloud-core)
Collecting ecdsa>=0.11 (from paramiko==1.16.0->cgcloud-core)
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Building wheels for collected packages: cgcloud-core, bd2k-python-lib, cgcloud-lib, subprocess32
  Running setup.py bdist_wheel for cgcloud-core ... done
  Stored in directory: /Users/dean/Library/Caches/pip/wheels/1b/1f/e2/5d126a8ff484288df9ebfc5834629d96f07b25a9a78220a264
  Running setup.py bdist_wheel for bd2k-python-lib ... done
  Stored in directory: /Users/dean/Library/Caches/pip/wheels/87/ba/58/a800483461c27cb060a12118adfe3a22edb6a918093c8a81e6
  Running setup.py bdist_wheel for cgcloud-lib ... done
  Stored in directory: /Users/dean/Library/Caches/pip/wheels/30/0d/6d/c9d5d2dfaf4be47d2c67024ac6874cd9ac3d1a100bd63e6080
  Running setup.py bdist_wheel for subprocess32 ... done
  Stored in directory: /Users/dean/Library/Caches/pip/wheels/7d/4c/a4/ce9ceb463dae01f4b95e670abd9afc8d65a45f38012f8030cc
Successfully built cgcloud-core bd2k-python-lib cgcloud-lib subprocess32
Installing collected packages: bd2k-python-lib, cgcloud-lib, futures, ecdsa, paramiko, Fabric, subprocess32, cgcloud-core
  Found existing installation: bd2k-python-lib 1.11.dev6
    Uninstalling bd2k-python-lib-1.11.dev6:
      Successfully uninstalled bd2k-python-lib-1.11.dev6
  Found existing installation: cgcloud-lib 1.3.8
    Uninstalling cgcloud-lib-1.3.8:
      Successfully uninstalled cgcloud-lib-1.3.8
  Found existing installation: paramiko 2.0.0
    Uninstalling paramiko-2.0.0:
      Successfully uninstalled paramiko-2.0.0
  Found existing installation: Fabric 1.10.2
    Uninstalling Fabric-1.10.2:
      Successfully uninstalled Fabric-1.10.2
  Found existing installation: cgcloud-core 1.3.8
    Uninstalling cgcloud-core-1.3.8:
      Successfully uninstalled cgcloud-core-1.3.8
Successfully installed Fabric-1.10.3 bd2k-python-lib-1.13.dev16 cgcloud-core-1.4a1.dev286 cgcloud-lib-1.4a1.dev286 ecdsa-0.13 futures-3.0.4 paramiko-1.16.0 subprocess32-3.2.7
```

**Comment by deanasnyder** [comment]
And the full output from the cgcloud call:

```
(cgcloud) $ cgcloud create -IT toil-box
INFO: Using zone 'us-east-1a' and namespace '/dean/'
INFO: Looking up default image for role toil-box and virtualization type hvm, ... 
INFO: ... found ami-0d729a60.
INFO: Setting up security group ...
INFO: ... finished setting up sg-62c3d975.
INFO: Creating t2.micro instance(s) ... 
Traceback (most recent call last):
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/bin/cgcloud", line 11, in <module>
    sys.exit(main())
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/lib/util.py", line 308, in run
    command.run( options )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 81, in run
    return self.run_in_ctx( options, cox )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 105, in run_in_ctx
    return self.run_on_role( options, ctx, role )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 124, in run_on_role
    return self.run_on_box( options, box )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 564, in run_on_box
    box.create( spec, **self.creation_kwargs( options, box ) )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 779, in create
    self.ctx.ec2.terminate_instances( unfinished_ids_list )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 723, in create
    num_instances=num_instances ) )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/lib/ec2.py", line 490, in create_ondemand_instances
    **spec ).instances
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VPCResourceNotSpecified</Code><Message>The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.</Message></Error></Errors><RequestID>92e4aa17-127a-461d-967e-5f5513b7efac</RequestID></Response>
```

**Comment by hannes-ucsc** [comment]
Since there seems to be no default VPC in your account, you would have to specify one explicitly using the `--vpc` command line argument (the one that PR #165 added) when you create your box:

```
cgcloud create -IT --vpc VPC_ID toil-box
```

If there is no VPC in the region you are trying to use, you need to create one manually using the VPC console:

http://docs.aws.amazon.com/AmazonVPC/latest/GettingStartedGuide/getting-started-create-vpc.html

Oh, and it seems that you installed cgcloud-toil. If that is the case it needs to be upgraded as well before you try the above:

```
pip install --upgrade --pre cgcloud-toil
```

When you run `pip list | grep cgcloud-`, all lines in the output should refer to the 1.4a1.dev286 version.

**Comment by deanasnyder** [comment]
Upgraded to the new packages:

>    cgcloud-core (1.4a1.dev286)
>    cgcloud-lib (1.4a1.dev286)
>    cgcloud-mesos (1.4a1.dev286)
>    cgcloud-spark (1.4a1.dev286)
>    cgcloud-toil (1.4a1.dev286)

Now I get the following new error - "Invalid value 'dean_toil-box' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation"

Here's the console output:

```
$ cgcloud create -IT --vpc vpc-d40d97b1 toil-box
INFO: Using zone 'us-east-1a' and namespace '/dean/'
INFO: Looking up default image for role toil-box and virtualization type hvm, ... 
INFO: ... found ami-0d729a60.
INFO: Setting up security group ...
Traceback (most recent call last):
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/bin/cgcloud", line 11, in <module>
    sys.exit(main())
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/lib/util.py", line 308, in run
    command.run( options )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 81, in run
    return self.run_in_ctx( options, cox )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 105, in run_in_ctx
    return self.run_on_role( options, ctx, role )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 124, in run_on_role
    return self.run_on_box( options, box )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 563, in run_on_box
    spec = box.prepare( **self.preparation_kwargs( options, box ) )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 477, in prepare
    security_group_ids = self.__setup_security_groups( vpc_id=vpc_id )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 328, in __setup_security_groups
    assert self.ctx.ec2.authorize_security_group( group_name=sg.name, **rule )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/ec2/connection.py", line 3191, in authorize_security_group
    params, verb='POST')
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'dean_toil-box' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation.</Message></Error></Errors><RequestID>2f5e80bc-d832-4b78-8210-74aaa0971a34</RequestID></Response>
```

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/cgcloud/pull/171 should address this. I will report back here when it is merged and ready to be tested. Thanks for your continued help with this.

**Comment by hannes-ucsc** [comment]
#171 has been merged and release 1.4a1.dev288 is ready for testing.

**Comment by deanasnyder** [comment]
Now we get a different, but similar error: "An IP permission for a VPC security group may only include a group ID, not a group name". I guess you need to use IDs **everywhere**.

$ pip list | grep cgcloud-

> cgcloud-core (1.4a1.dev288)
> cgcloud-lib (1.4a1.dev288)
> cgcloud-mesos (1.4a1.dev288)
> cgcloud-spark (1.4a1.dev288)
> cgcloud-toil (1.4a1.dev288)

$ cgcloud create -IT --vpc vpc-d40d97b1 toil-box

```
INFO: Using zone 'us-east-1a' and namespace '/dean/'
INFO: Looking up default image for role toil-box and virtualization type hvm, ... 
INFO: ... found ami-0d729a60.
INFO: Setting up security group ...
Traceback (most recent call last):
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/bin/cgcloud", line 11, in <module>
    sys.exit(main())
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/lib/util.py", line 308, in run
    command.run( options )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 81, in run
    return self.run_in_ctx( options, cox )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 105, in run_in_ctx
    return self.run_on_role( options, ctx, role )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 124, in run_on_role
    return self.run_on_box( options, box )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/commands.py", line 563, in run_on_box
    spec = box.prepare( **self.preparation_kwargs( options, box ) )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 477, in prepare
    security_group_ids = self.__setup_security_groups( vpc_id=vpc_id )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/cgcloud/core/box.py", line 328, in __setup_security_groups
    assert self.ctx.ec2.authorize_security_group( group_id=sg.id, **rule )
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/ec2/connection.py", line 3191, in authorize_security_group
    params, verb='POST')
  File "/Users/dean/Documents/CIDR/ADAM/cgcloud/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>An IP permission for a VPC security group may only include a group ID, not a group name.</Message></Error></Errors><RequestID>cfbc157c-d821-43a0-b1b1-89e77b64dca1</RequestID></Response>
```

**Comment by hannes-ucsc** [comment]
Sorry for the back and forth. I should have tested this locally.

**Comment by hannes-ucsc** [comment]
Another PR is coming. I've tested it and it gets passed the instance creation now. 

However, the user needs to make sure that their VPC is fully setup. Naively, I just created a VPC and three subnets and cgcloud hangs waiting for public IP to be assigned. It turns out that by default, subnets don't do that:

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-ip-addressing.html#subnet-public-ip

After I fixed that, the public IP was assigned but the public DNS hostname wasn't. The custom VPC needs to be changed to fix that:

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html#vpc-dns-updating

Lastly, there also needs to be at least one NAT gateway in the VPC, ideally one per availability zone. Without it, the instance won't be able to reach the outside world and cgcloud will hang waiting for SSH to be functional.

**Comment by hannes-ucsc** [comment]
Scratch the last paragraph. There should be one Internet Gateway attached to the VPC and a default route pointing at that gateway in the routing table for that VPC. The table was created automatically for me but I had to manually add the gateway and the corresponding routing table entry.

**Comment by hannes-ucsc** [comment]
1.4a1.dev295 contains a fix for the `You may not reference Amazon VPC security groups by name` issue and for another unrelated issue (#173) with `toil-box`. @deanasnyder, could you give it a whirl?

**Comment by deanasnyder** [comment]
Wow! Am I impressed! After updating my installation to your latest fixes I ran 

> $ cgcloud create -IT --vpc vpc-d40d97b1 toil-box

without implementing the AWS VPC fixes you wrote about in one of your recent posts:

> the user needs to make sure that their VPC is fully setup. Naively, I just created a VPC and three subnets and cgcloud hangs waiting for public IP to be assigned. It turns out that by default, subnets don't do that ...
> 
> After I fixed that, the public IP was assigned but the public DNS hostname wasn't. The custom VPC needs to be changed to fix that ...
> 
> Lastly, there also needs to be at least one NAT gateway in the VPC, ideally one per availability zone. Without it, the instance won't be able to reach the outside world and cgcloud will hang waiting for SSH to be functional.

So, just as you indicated, the script hung and I sat there waiting at the following step:

> INFO: ... waiting for instance i-d98c0f43 ... 
> INFO: ... running, waiting for assignment of public IP ... 

After working on some other stuff for about 15 minutes, and without interrupting the script running in the terminal, I then went to the AWS console in the browser and implemented the steps you outlined. And, voila, I see, in real time, the very next step happening in the terminal!:

> INFO: ... assigned, waiting for SSH port 
> ... 

And ultimately the Toil box was indeed successfully created.

Thanks much!

I have one further question, do I need to add the --vpc argument to "cgcloud create-cluster toil -s 2"?

**Comment by hannes-ucsc** [comment]
> do I need to add the --vpc argument to "cgcloud create-cluster toil -s 2"?

Yes.

I'm debating whether there should be a CGCLOUD_VPC environment variable so it doesn't have to be passed around everywhere.

**Comment by deanasnyder** [comment]
Sounds attractive - although, wouldn't this complicate interacting with, managing, and monitoring multiple clusters running in different VPCs? (I guess you could default to a CGCLOUD_VPC environment variable in the absence of a specified one. But I think that personally I would find the explicitly-specified-everywhere VPC more useful.)
