### ISSUE TITLE
Add toil-scripts to ToilBox

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/cgcloud#176]
Relies on BD2KGenomics/toil-scripts#267

**Comment by hannes-ucsc** [comment]
Is this really necessary? This would install toil-scripts on every node in a cluster while it really is only needed the leader.

There is a problem with manually installing toil-scripts on the leader in a virtualenv. If done naively, a duplicate, potentially conflicting version of Toil would be installed in that virtualenv, while what you really want is for the virtualenv to inherit the globally installed version of Toil that ToilBox ships with. Someone with in-depth knowledge of Python packaging should actually try this out.

I almost feel that toil-scripts' `setup.py` should not explicitly declare a `install_requires` dependency on toil. Rather, it should explicitly check for Toil's existence and version before calling `setup()`.

**Comment by jvivian** [comment]
> This would install toil-scripts on every node in a cluster while it really is only needed the leader.

Trying to run the pipeline on a mesos leader / worker failed unless toil-scripts was installed on the worker.  BD2KGenomics/toil-scripts#291

**Comment by hannes-ucsc** [comment]
Please file a ticket against Toil with concrete steps for a reproduction. Toil's hot-deployment should make it unnecessary to install the user script/module on each worker. This used to work for the TCGA recompute and we need to find out why it's not working anymore.

**Comment by hannes-ucsc** [comment]
Also, when installing toil-scripts on the leader, be sure that you fully understand the interaction between the virtualenv and the global installation of Toil on a ToilBox instance. This interaction could be the cause of the issue you allude to in BD2KGenomics/toil-scripts#291.

**Comment by fnothaft** [comment]
To echo @hannes-ucsc, this seems like treating the symptoms, not the underlying problem. If hot deployment is broken, that seems like a showstopper bug in Toil.

**Comment by jvivian** [comment]
@hannes-ucsc — Can you detail how you would install toil-scripts in venv to avoid this conflict? 

I've run into issues using a venv and since toil-scripts setup.py checks for toil==3.1.4, which is the version on the toil-box image I'm using, there's no conflicts installing it outside of a venv.

**Comment by hannes-ucsc** [comment]
The toil-scripts virtualenv should be created with `--system-site-packages` such that the globally installed Toil is inherited. Then care needs to be taken to ensure that pip doesn't replace the globally installed Toil by installing a copy into the virtualenv. It is entirely possible that even those two things don't work. 

You keep mentioning "issues" but without you actually filing those issues on GH against Toil we will be going in circles.

We can also change cgcloud to install Toil into a venv itself if that makes it easier.

**Comment by jvivian** [comment]
> You keep mentioning "issues" but without you actually filing those issues on GH against Toil we will be going in circles.

I didn't want to open superfluous issues until I knew I was doing it correctly. 

**Laptop**

```
cgcloud create-cluster --instance-type m3.large --leader-instance-type m3.large --spot-bid 1.00 --num-workers 1 toil

cgcloud ssh toil-leader
```

**Leader**

```
virtualenv --system-site-packages piptest

source piptest/bin/activate

pip install --pre toil-scripts
-----------------------------------
Collecting toil-scripts
Requirement already satisfied (use --upgrade to upgrade): boto==2.38.0 in /usr/local/lib/python2.7/dist-packages (from toil-scripts)
Requirement already satisfied (use --upgrade to upgrade): toil==3.1.4 in /usr/local/lib/python2.7/dist-packages (from toil-scripts)
Collecting pyyaml==3.11 (from toil-scripts)
Collecting tqdm==3.8.0 (from toil-scripts)
  Using cached tqdm-3.8.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): bd2k-python-lib==1.10.dev6 in /usr/local/lib/python2.7/dist-packages (from toil==3.1.4->toil-scripts)
Installing collected packages: pyyaml, tqdm, toil-scripts
  Found existing installation: PyYAML 3.10
    Not uninstalling pyyaml at /usr/lib/python2.7/dist-packages, outside environment /home/mesosbox/piptest
Successfully installed pyyaml-3.11 toil-scripts-2.0a2.dev179 tqdm-3.8.0
```

While pip says the requirement is already satisfied, something is wrong with the installation as Toil complains that it can't find an entrypoint:

```
INFO:toil.leader:Starting the main loop
Traceback (most recent call last):
  File "./piptest/bin/toil-rnaseq", line 11, in <module>
    sys.exit(main())
  File "/home/mesosbox/piptest/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 638, in main
    Job.Runner.startToil(Job.wrapJobFn(map_job, download_sample, samples, config), args)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 445, in startToil
    return mainLoop(config, batchSystem, jobStore, rootJob, jobCache=jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 392, in mainLoop
    jobWrapper.cores, jobWrapper.disk)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 101, in issueJob
    jobCommand = ' '.join((resolveEntryPoint('_toil_worker'), self.jobStoreString, jobStoreID))
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 45, in resolveEntryPoint
    assert os.path.isfile(path)
AssertionError
```

This error _doesn't_ appear and the pipeline can run locally if toil-scripts is installed outside of a venv.

**Comment by hannes-ucsc** [comment]
> I didn't want to open superfluous issues until I knew I was doing it correctly.

If I were you, I'd err on the side of escalating problems to GH issues so other people can take a look rather than jumping to conclusions all by yourself.

Please create a Toil issue with the information you list above.

**Comment by jvivian** [comment]
I have created tickets BD2KGenomics/Toil#929 and BD2KGenomics/Toil#930.    The first addresses an error that comes from running toil-scripts inside a venv, and the second describes the issue of running toil-scripts on a mesos cluster.

I agree with @fnothaft about this treating the symptom — @hannes-ucsc, can I close this issue?
