### ISSUE TITLE
A few misc fixes for Spark/Toil testing

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/cgcloud#189]
We need to make a few changes to the Toil Jenkins worker:
- Set SPARK_HOME
- Downgrade to Spark 1.5.2

These are needed to properly connect pyspark to the Spark JVM client, and then to get the Spark JVM to talk to the Docker-based Standalone Spark cluster. We will need these for https://github.com/BD2KGenomics/toil/pull/786. I'll take them on tomorrow AM; they should be really quick.

**Comment by hannes-ucsc** [comment]
Officially, I won't be working tomorrow but I'll squeeze in a few minutes to review your PR.

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc! The patch has Hamming edit distance of 2, so it should hopefully not take too much time to review. Hope you have a good off day.
