### ISSUE TITLE
ssh-cluster unable to sudo pip install

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/cgcloud#211]
Trying to use cgcloud to test out the new exome pipeline... 

It needs a few pip installations but I keep getting an error from cgcloud ssh-cluster toil -a sudo pip install synapseclient

INFO: === Performing operation on leader ===
sudo: no tty present and no askpass program specified
INFO: === Performing operation on workers ===
sudo: no tty present and no askpass program specified

**Comment by jvivian** [comment]
The `-a` comes before `toil`, otherwise it's being passed as part of the SSH command.

**Comment by dyollluap** [comment]
Thanks!
