### ISSUE TITLE
Move cgcloud-spark to Spark 1.6.1, Java 8

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/cgcloud#231]
We'd like this downstream in ADAM (https://github.com/bigdatagenomics/adam/issues/493) for plain AWS deploy for ADAM ToT. I'll see if there's a good way to do this that also pulls in https://github.com/BD2KGenomics/cgl-docker-lib/pull/187.

**Comment by jpdna** [comment]
Pinging on this - cgcloud ADAM deploy doc #493 is blocked on this at moment.

**Comment by fnothaft** [comment]
> Pinging on this - cgcloud ADAM deploy doc #493 is blocked on this at moment.

Let me get this today. We were doing a complex change up in https://github.com/BD2KGenomics/cgl-docker-lib/issues/196, but @almussel's comment makes it seem like we may not need that change after all.

**Comment by hannes-ucsc** [comment]
Do we need to keep supporting the old versions of Spark and Java? I'd much rather not but am asking out of due diligence. Is there a scenario in which someone would not want to upgrade from 1.5.x?

**Comment by fnothaft** [comment]
Ping for merge @hannes-ucsc
