### ISSUE TITLE
Problem with Spark monitoring

### ISSUE THREAD

**Issue by hyviquel** [BD2KGenomics/cgcloud#236]
I have not succeed to configure the web UI to keep monitoring information after the execution of the application, even with `spark.eventLog.enabled true` in `conf/spark-defaults.conf`.
I tried to set up `spark.eventLog.dir`both to local directory and hdfs one...
Anyone already met the problem ?
I don't know if this is the problem but I update cgcloud to use spark 2.0.1 and hadoop 2.7.3

**Comment by hannes-ucsc** [comment]
Does this happen on a vanilla master, without any changes?

**Comment by hannes-ucsc** [comment]
If you want help with this, I propose that you file a PR with the changes you mentioned (upgrading Spark and Hadoop). We can then see if this replicates on our continuous integration server.
