### ISSUE TITLE
core/README.md adding command to .profile gives error

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#63]
I ran pip install argcomplete via virtualenv, as suggested.

From the README:

`Then add the following command to your ~/.profile:`
`eval "$(register-python-argcomplete cgcloud)"`

However, adding this to my .(bash_)profile results in an unpleasant error when I ssh to the machine:
`-bash: register-python-argcomplete: command not found`

This makes sense, since I'm not in my virtualenv yet. But it's a bit ugly! Is there a prettier solution?

**Comment by hannes-ucsc** [comment]
`eval "$(register-python-argcomplete /absolute/path/to/virtualenv/bin/cgcloud)"`

**Comment by hannes-ucsc** [comment]
Could you try again but with the absolute path to the cgcloud script in your virtualenv's bin subdirectory.

**Comment by Jeltje** [comment]
That doesn't work, but this does:
`eval "$(/absolute/path/to/virtualenv/bin/register-python-argcomplete cgcloud)"`
I also tried it with the full path to cgcloud (as in your example), but it appears to work with any argument instead of cgcloud, so I don't know what that's worth...

**Comment by hannes-ucsc** [comment]
Brilliant. So we need to change the README to reflect this. I'm almost tempted to change the READMEs such that virtualenv is the default for all the code examples. A knowledgeable user should then be able to translate the instructions to a per-user or a global install.

@Jeltje feel free to take this issue on

**Comment by hannes-ucsc** [comment]
Closed by 902d86ffe008112534991085957dbb7f15bd21bc
