### ISSUE TITLE
pip install error on Ubuntu 14.04

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#69]
```
virtualenv cgcloud
source cgcloud/bin/activate
pip install cgcloud-core
```

leads to 

```
Traceback (most recent call last):
  File "/data/cgcloud/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/data/cgcloud/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/data/cgcloud/local/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/data/cgcloud/local/lib/python2.7/site-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for cgcloud-core
```

Same issue for `pip install cgcloud-spark`
I do not see the same issue on CentOS.

**Comment by hannes-ucsc** [comment]
Could you try `pip install --pre cgcloud-core`?

I have the feeling pip recently changed the way it treats pre-releases.

And is this on a generic-ubuntu-trusty-box or some other system? If the latter, could you post the output of `pip list`?

**Comment by Jeltje** [comment]
`pip install --pre cgcloud-core` works fine

`pip list`  before install:

```
argparse (1.2.1)
pip (1.5.4)
setuptools (2.2)
wsgiref (0.1.2)
```

**Comment by hannes-ucsc** [comment]
This will be fixed once we have a non-pre release of cgcloud. However, the quirk should be mentioned in the README. I'll leave this issue open to track that change.

**Comment by Jeltje** [comment]
I should add that I currently have the same issue (with the same solution) when running `pip install s3am`
I'm happy to create an issue over there - say the word.

**Comment by hannes-ucsc** [comment]
Yes, issue against s3am would be great. Don't much explanation, just a link to this issue here.

**Comment by Jeltje** [comment]
Looks like John V already did -> [issue  #15](https://github.com/BD2KGenomics/s3am/issues/15)
