### ISSUE TITLE
Incorrect command order in spark/README

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#70]
from spark/README.rst:

```
cgcloud ssh spark-slave -o 0
```

gives `unknown option -- -`

This works:

```
cgcloud ssh -o 0 spark-slave
```

I can change the README & do pull request but I want to make sure this is not a local issue I'm having (running on Ubuntu 14.04)

**Comment by hannes-ucsc** [comment]
This is a problem in the documentation. I'll fix it right away.
