### ISSUE TITLE
pip install cgcloud-bd2k-ci not possible

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#74]
after pip installing cgcloud-core, cgcloud-toil, cgcloud-mesos and s3am (all with `--pre` because otherwise I got errors), I tried 

`cgcloud --help`
and got

```
ERROR: Cannot find plugin module 'cgcloud.bd2k.ci'. Running 'pip install cgcloud-bd2k-ci' may fix this.
```

However, `pip install  cgcloud-bd2k-ci` (with and without `--pre`) results in 

```
Could not find any downloads that satisfy the requirement cgcloud-bd2k-ci
Cleaning up...
No distributions at all found for cgcloud-bd2k-ci
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

I then noticed I'd not installed toil itself, so did `pip install toil`
But then `cgcloud --help`

```
Traceback (most recent call last):
  File "/data/git/toil_varscan/venv/bin/cgcloud", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/data/git/toil_varscan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(__requires__), Environment()
  File "/data/git/toil_varscan/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: bd2k-python-lib==1.10.dev4

```

`pip list`

```
argparse (1.2.1)
bd2k-python-lib (1.7.dev1)
boto (2.38.0)
cgcloud-core (1.1a1.dev143)
cgcloud-lib (1.1a1.dev143)
cgcloud-mesos (1.1a1.dev143)
cgcloud-toil (1.1a1.dev143)
ecdsa (0.13)
Fabric (1.10.2)
paramiko (1.15.3)
pip (1.5.4)
pycrypto (2.6.1)
pycurl (7.19.5.1)
PyYAML (3.11)
s3am (1.0b1.dev29)
setuptools (2.2)
toil (3.0.7)
wsgiref (0.1.2)
```

So obviously `bd2k-python-lib (1.7.dev1)` is not correct. However, `pip install toil --pre` results in `1.9.dev1`, NOT `1.10.dev4`.

I guess this is really two issues: the error message isn't helpful, and the latest version of the bd2k python lib is not in pip.

**Comment by hannes-ucsc** [comment]
On Oct 18, I sent an email about this to all known cgcloud users. Subject line was "You may need to update CGCLOUD_PLUGINS":

> After upgrading to latest master or "pip install"-ing version 1.1a1.dev137 or higher, an occurrence of the string "cgcloud.bd2k.ci" in the environment variable CGCLOUD_PLUGINS needs to be replaced with the string "cgcloud.jenkins". 
> 
> The modification to cgcloud that makes this replacement necessary fixes an inconsistency that has caused—and would have continued to cause— confusion with new users of cgcloud.

Closing this for now. Please reopen if the above does not fix the problem.

**Comment by Jeltje** [comment]
Doh! That, and `pip install cgcloud-jenkins --pre` fixed my problem. Thanks.
