### ISSUE TITLE
Docker container fills worker's /dev/xvda1

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#76]
docker run jvivian/bedtools coverage fills up /dev/xvda1 on the toil worker

This is using cgcloud-core (1.1a1.dev143), see below for full pip list

To reproduce:

`git clone https://github.com/Jeltje/mytoilscripts.git`
`cd mytoilscripts`
`mkdir key_config`
create 
    `key_config/master.key`
    `key_config/config.txt` with this line:
`DTB_005_BL_T,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/wcdt/exome_bams/DTB-005-BL-T.bam`

`cgcloud create-toil-cluster --master-instance-type m3.medium -t=r3.xlarge -s=1 --shared-dir=key_config/`
`cgcloud rsync toil-leader wrapCov.sh :`
`cgcloud rsync toil-leader toil_coverage.py :`

Log on to leader and run `./wrapCov.sh`

Log on to worker, wait for the 11.1 G bam file to finish downloading in /var/lib/toil/tmp<>/localTempDir/, then watch `/dev/xvda1` fill up (starting after about 20 minutes).

This behavior can be avoided by logging on to the worker as user ubuntu and running

`sudo service docker.io stop && sleep 10 && sudo mv /var/lib/docker /mnt/ephemeral/var/lib/ && sudo mkdir /var/lib/docker && sudo mount --bind /mnt/ephemeral/var/lib/docker /var/lib/docker && sudo service docker.io start`

`pip list`

```
argparse (1.2.1)
bd2k-python-lib (1.10.dev4)
boto (2.38.0)
cgcloud-core (1.1a1.dev143)
cgcloud-jenkins (1.1a1.dev143)
cgcloud-lib (1.1a1.dev143)
cgcloud-mesos (1.1a1.dev143)
cgcloud-toil (1.1a1.dev143)
ecdsa (0.13)
Fabric (1.10.2)
paramiko (1.15.3)
pip (1.5.4)
pycrypto (2.6.1)
pycurl (7.19.5.1)
PyYAML (3.11)
s3am (1.0b1.dev29)
setuptools (2.2)
toil (3.1.0b1.dev55)
wsgiref (0.1.2)
```

**Comment by hannes-ucsc** [comment]
I have the feeling that this happens because you are using a toil-box image that was created with an older version of cgcloud. Could you try this again after running `cgcloud create -IT toil-box`?

**Comment by Jeltje** [comment]
Tried it, same problem.

**Comment by hannes-ucsc** [comment]
An observation: Version 1.1a1.dev143 of Toil contains commit 00f0bce1943f9c88104f534adb0758071949b390 which changed the service name from `docker.io` to `docker`. But the workaround still uses `docker.io` and therefore should fail right away in `sudo service docker.io stop`.

**Comment by hannes-ucsc** [comment]
0cdebc26405385803ff8ab693385715627ec8cf3
