### ISSUE TITLE
core dump from python code on toil master

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#81]
Originally reported as BD2KGenomics/toil-scripts#58

I tried it with my varscan code, which worked fine before, and get the same `invalid pointer` issue.

My setup:
`cgcloud create-cluster --leader-instance-type m3.medium -t=c3.8xlarge -s 1 --share key_config/ toil`

`pip list`

```
argparse (1.2.1)
bd2k-python-lib (1.10.dev5)
boto (2.38.0)
cgcloud-core (1.2.2)
cgcloud-jenkins (1.2.2)
cgcloud-lib (1.2.2)
cgcloud-mesos (1.2.2)
cgcloud-toil (1.2.2)
ecdsa (0.13)
Fabric (1.10.2)
paramiko (1.16.0)
pip (1.5.4)
pycrypto (2.6.1)
pycurl (7.19.5.3)
PyYAML (3.11)
s3am (1.0b1.dev30)
setuptools (2.2)
wsgiref (0.1.2)
```

```
> echo $CGCLOUD_PLUGINS
cgcloud.toil:cgcloud.jenkins:cgcloud.mesos
```

**Comment by hannes-ucsc** [comment]
I'm not convinced that this is a cgcloud issue.

**Comment by Jeltje** [comment]
Turned out to be an outdated toil master issue
